### ISSUE TITLE
no return with large records csv

### ISSUE THREAD

**Issue by hunuyolau** [vladimiriii/jsonify-it#2]
Iam trying to use jsonify to convert my csv data set to a Json in your website. my data set has around 24000 rows. after i complete all the setting and press run, it does not return any result (keep staying in the "JSON will display here" screen)

i tried with a hundred up to 6000 records. it works normally.

starting from 8000 records. it starts to no return

**Comment by brettromero** [comment]
Larger datasets can mean there is a delay in producing and displaying the results. If you have a lot of columns, and/or large text values, a dataset with 'only' 24,000 rows can still be 10s of MBs. But I have tested the tool with datasets over 30,000 rows and it still works. You just have to wait on the "JSON will display here" screen for the result to display. Keep in mind it is literally loading multiple MBs of data into the page so it just takes time, particularly if you are on a slower connection.
