### ISSUE TITLE
Large Datasets

### ISSUE THREAD

**Issue by IamManifold** [vladimiriii/jsonify-it#5]
Hello, 
First I want to thank you for this awesome tool, it's by far the bet converter i've seen. 
I'm running into issues running larger datasets through your site (the final json, doesn't load), so i decided to try to load up my own server for it but not being a python guy, i feel like i'm missing something. 
I've opened a bash console, navigated to the directory, ran the install and run command but getting an error, I'm thinking it's an issue with my python installation but i really don't know. 
`$ bash run.sh
run.sh: line 1: ./venv/bin/activate: No such file or directory
Traceback (most recent call last):
  File "run.py", line 6, in <module>
    app = create_app()
  File "C:\python38\jsonify-it-master\app\__init__.py", line 12, in create_app
    load_config(app)
  File "C:\python38\jsonify-it-master\app\__init__.py", line 41, in load_config
    app.config['SERVER_PORT'] = config.get('Application', 'SERVER_PORT')
  File "C:\Python38\lib\configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "C:\Python38\lib\configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'Application'
`

I tried doing it in it's own directory originally but still have the same issues. I hate to post an issue here when it's probably on my side but this was the only way i could find to submit something. 

Any help would be greatly appreciated.

**Comment by vladimiriii** [comment]
Hi Justin - the error message suggests that the install step didn't work. If `bash install.sh` runs successfully, you should be able to see a folder `venv` in the base directory of the repo. That folder will contain all the python libraries you need to run the app. Do you get an error message when you run the install script? Does it create the folder and sub directories?

**Comment by vladimiriii** [comment]
How large is the data set by the way? The website can handle pretty large datasets, but you might just have to wait for a while.
