### ISSUE TITLE
A Sample document with example using data needed

### ISSUE THREAD

**Issue by gouravbhatt** [vladimiriii/jsonify-it#6]
A Sample document with example  on how to use it like what will be data and how to convert into nested Json

**Comment by vladimiriii** [comment]
Yeah, good idea. I'm taking a look at doing this, just a question of time. :)

**Comment by vladimiriii** [comment]
OK, finally got around to this, added an [examples page](https://jsonifyit.com/csv-to-json-examples) which walks through some of the options. Hope that helps!
