### ISSUE TITLE
Nesting

### ISSUE THREAD

**Issue by jeffthomas999** [vladimiriii/jsonify-it#7]
I have a sample file json file (below) I am trying to play with and replicate with my data to figure out nesting within nesting. I have entered my data into your program and can get the first nest to work ("movies"), but I can't figure out how to create the second nest ("content").

Thank you.

The following is the sample format for what I am trying to accomplish:

{
	"providerName": \"Roku Direct Publisher Sample Feed\",
	"language": "en-US",
	"lastUpdated": "2020-03-06,
**"movies": [{**

			"id": "rsg-unit2-developerSetup",
			"title": "Development setup",
			"content": {
				"dateAdded": "2020-07-21T02:32:24Z",
				"videos": [{
					"videoType": "MP4",
					"url": "https://image.roku.com/ZHZscHItMTc2/rsg-unit2-developerSetup-v4.mp4",
					"quality": "HD"
				}],
				"duration": 431,
				"language": "en-us"
			},
			"thumbnail": "https://image.roku.com/ZHZscHItMTc2/rsg-unit2-developerSetup-v4.png",
			"shortDescription": "Start developing for the Roku platform. This lesson explains the first steps.",
			"releaseDate": "2020-07-20",
			"longDescription": "Start developing for the Roku platform. This lesson explains the first steps, which includes creating the required user and developer accounts and enabling your test Roku device for development. Once you're done, you can sideload Roku's Hello World channel and view its output in the debug console.",
			"tags": [
				"rsg_row"
			],
			"genres": [
				"educational"
			]
		},

**Comment by vladimiriii** [comment]
How is the CSV structured?
